INSERT INTO cidades (id, nome, "estadoId", "createdAt", "updatedAt", active)
VALUES
    (1, 'Porto Velho', 11, NOW(), NOW(), TRUE),
    (2, 'Ji-Parana', 11, NOW(), NOW(), TRUE),
    (3, 'Ariquemes', 11, NOW(), NOW(), TRUE),
    (4, 'Rio Branco', 12, NOW(), NOW(), TRUE),
    (5, 'Cruzeiro do Sul', 12, NOW(), NOW(), TRUE),
    (6, 'Manaus', 13, NOW(), NOW(), TRUE),
    (7, 'Parintins', 13, NOW(), NOW(), TRUE),
    (8, 'Itacoatiara', 13, NOW(), NOW(), TRUE),
    (9, 'Boa Vista', 14, NOW(), NOW(), TRUE),
    (10, 'Rorainopolis', 14, NOW(), NOW(), TRUE),
    (11, 'Belem', 15, NOW(), NOW(), TRUE),
    (12, 'Ananindeua', 15, NOW(), NOW(), TRUE),
    (13, 'Santarem', 15, NOW(), NOW(), TRUE),
    (14, 'Maraba', 15, NOW(), NOW(), TRUE),
    (15, 'Macapa', 16, NOW(), NOW(), TRUE),
    (16, 'Santana', 16, NOW(), NOW(), TRUE),
    (17, 'Palmas', 17, NOW(), NOW(), TRUE),
    (18, 'Araguaina', 17, NOW(), NOW(), TRUE),
    (19, 'Gurupi', 17, NOW(), NOW(), TRUE),
    (20, 'Sao Luis', 21, NOW(), NOW(), TRUE),
    (21, 'Imperatriz', 21, NOW(), NOW(), TRUE),
    (22, 'Caxias', 21, NOW(), NOW(), TRUE),
    (23, 'Teresina', 22, NOW(), NOW(), TRUE),
    (24, 'Parnaiba', 22, NOW(), NOW(), TRUE),
    (25, 'Picos', 22, NOW(), NOW(), TRUE),
    (26, 'Fortaleza', 23, NOW(), NOW(), TRUE),
    (27, 'Caucaia', 23, NOW(), NOW(), TRUE),
    (28, 'Juazeiro do Norte', 23, NOW(), NOW(), TRUE),
    (29, 'Sobral', 23, NOW(), NOW(), TRUE),
    (30, 'Natal', 24, NOW(), NOW(), TRUE),
    (31, 'Mossoro', 24, NOW(), NOW(), TRUE),
    (32, 'Parnamirim', 24, NOW(), NOW(), TRUE),
    (33, 'Joao Pessoa', 25, NOW(), NOW(), TRUE),
    (34, 'Campina Grande', 25, NOW(), NOW(), TRUE),
    (35, 'Patos', 25, NOW(), NOW(), TRUE),
    (36, 'Recife', 26, NOW(), NOW(), TRUE),
    (37, 'Jaboatao dos Guararapes', 26, NOW(), NOW(), TRUE),
    (38, 'Olinda', 26, NOW(), NOW(), TRUE),
    (39, 'Caruaru', 26, NOW(), NOW(), TRUE),
    (40, 'Petrolina', 26, NOW(), NOW(), TRUE),
    (41, 'Maceio', 27, NOW(), NOW(), TRUE),
    (42, 'Arapiraca', 27, NOW(), NOW(), TRUE),
    (43, 'Rio Largo', 27, NOW(), NOW(), TRUE),
    (44, 'Aracaju', 28, NOW(), NOW(), TRUE),
    (45, 'Nossa Senhora do Socorro', 28, NOW(), NOW(), TRUE),
    (46, 'Lagarto', 28, NOW(), NOW(), TRUE),
    (47, 'Salvador', 29, NOW(), NOW(), TRUE),
    (48, 'Feira de Santana', 29, NOW(), NOW(), TRUE),
    (49, 'Vitoria da Conquista', 29, NOW(), NOW(), TRUE),
    (50, 'Camacari', 29, NOW(), NOW(), TRUE),
    (51, 'Juazeiro', 29, NOW(), NOW(), TRUE),
    (52, 'Belo Horizonte', 31, NOW(), NOW(), TRUE),
    (53, 'Uberlandia', 31, NOW(), NOW(), TRUE),
    (54, 'Contagem', 31, NOW(), NOW(), TRUE),
    (55, 'Juiz de Fora', 31, NOW(), NOW(), TRUE),
    (56, 'Betim', 31, NOW(), NOW(), TRUE),
    (57, 'Montes Claros', 31, NOW(), NOW(), TRUE),
    (58, 'Vitoria', 32, NOW(), NOW(), TRUE),
    (59, 'Vila Velha', 32, NOW(), NOW(), TRUE),
    (60, 'Serra', 32, NOW(), NOW(), TRUE),
    (61, 'Cariacica', 32, NOW(), NOW(), TRUE),
    (62, 'Rio de Janeiro', 33, NOW(), NOW(), TRUE),
    (63, 'Sao Goncalo', 33, NOW(), NOW(), TRUE),
    (64, 'Duque de Caxias', 33, NOW(), NOW(), TRUE),
    (65, 'Nova Iguacu', 33, NOW(), NOW(), TRUE),
    (66, 'Niteroi', 33, NOW(), NOW(), TRUE),
    (67, 'Sao Paulo', 35, NOW(), NOW(), TRUE),
    (68, 'Guarulhos', 35, NOW(), NOW(), TRUE),
    (69, 'Campinas', 35, NOW(), NOW(), TRUE),
    (70, 'Sao Bernardo do Campo', 35, NOW(), NOW(), TRUE),
    (71, 'Santo Andre', 35, NOW(), NOW(), TRUE),
    (72, 'Osasco', 35, NOW(), NOW(), TRUE),
    (73, 'Curitiba', 41, NOW(), NOW(), TRUE),
    (74, 'Londrina', 41, NOW(), NOW(), TRUE),
    (75, 'Maringa', 41, NOW(), NOW(), TRUE),
    (76, 'Ponta Grossa', 41, NOW(), NOW(), TRUE),
    (77, 'Cascavel', 41, NOW(), NOW(), TRUE),
    (78, 'Florianopolis', 42, NOW(), NOW(), TRUE),
    (79, 'Joinville', 42, NOW(), NOW(), TRUE),
    (80, 'Blumenau', 42, NOW(), NOW(), TRUE),
    (81, 'Sao Jose', 42, NOW(), NOW(), TRUE),
    (82, 'Criciuma', 42, NOW(), NOW(), TRUE),
    (83, 'Porto Alegre', 43, NOW(), NOW(), TRUE),
    (84, 'Caxias do Sul', 43, NOW(), NOW(), TRUE),
    (85, 'Canoas', 43, NOW(), NOW(), TRUE),
    (86, 'Pelotas', 43, NOW(), NOW(), TRUE),
    (87, 'Santa Maria', 43, NOW(), NOW(), TRUE),
    (88, 'Campo Grande', 50, NOW(), NOW(), TRUE),
    (89, 'Dourados', 50, NOW(), NOW(), TRUE),
    (90, 'Tres Lagoas', 50, NOW(), NOW(), TRUE),
    (91, 'Cuiaba', 51, NOW(), NOW(), TRUE),
    (92, 'Varzea Grande', 51, NOW(), NOW(), TRUE),
    (93, 'Rondonopolis', 51, NOW(), NOW(), TRUE),
    (94, 'Goiania', 52, NOW(), NOW(), TRUE),
    (95, 'Aparecida de Goiania', 52, NOW(), NOW(), TRUE),
    (96, 'Anapolis', 52, NOW(), NOW(), TRUE),
    (97, 'Rio Verde', 52, NOW(), NOW(), TRUE),
    (98, 'Brasilia', 53, NOW(), NOW(), TRUE),
    (99, 'Taguatinga', 53, NOW(), NOW(), TRUE),
    (100, 'Ceilandia', 53, NOW(), NOW(), TRUE)
ON CONFLICT (id) DO UPDATE
SET nome = EXCLUDED.nome,
    "estadoId" = EXCLUDED."estadoId",
    "updatedAt" = NOW(),
    active = TRUE;

SELECT setval(pg_get_serial_sequence('cidades', 'id'), GREATEST((SELECT MAX(id) FROM cidades), 1), TRUE);
